baseURL: "https://platformlabs.co/"
theme: "up-business-theme-edited"
languageCode: "en-us"

title: "platformlabs.co"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "platformlabs.co"
  description: "developer enablement is our passion"
  images: 
    - "logo.png"

  logo: "favicon.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:

  location:
    - "Rio de Janeiro, Brazil"

  contact:
    - "info@platformlabs.co"

  copyright: "© 2024 platformlabs.co All Rights Reserved"

taxonomies:
  series: "series"
  tags: "tags"
